# Generated by Django 5.0.13 on 2025-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
    ]
