services:
  db:
    image: postgres:17
    container_name: db-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web-container
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./kennel/media:/app/media
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - ./kennel/media:/media:ro
    depends_on:
      - web
volumes:
  postgres_data:
