"""
Django settings for kennel project.

Generated by 'django-admin startproject' using Django 5.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "DJANGO_CSRF_TRUSTED_ORIGINS", "https://cod-ex.ru"
).split(",")

DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# # Указывает Django использовать HTTPS при генерации ссылок и перенаправлении
# SECURE_SSL_REDIRECT = not DEBUG # Перенаправляет на HTTPS
#
# # Указывает Django использовать заголовок HTTP Strict Transport Security (HSTS)
# SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # Включает HSTS на 1 год
# SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG  # Включает для поддоменов
# SECURE_HSTS_PRELOAD = not DEBUG  # Для включения в preload list браузеров
#
# # Указывает браузерам отправлять куки только через защищенное HTTPS-соединение
# SESSION_COOKIE_SECURE = not DEBUG # Куки только через HTTPS
# CSRF_COOKIE_SECURE = not DEBUG # CSRF-токен только через HTTPS
#
# # Указывает Django использовать безопасные куки
# SECURE_BROWSER_XSS_FILTER = not DEBUG # Включает XSS-фильтр (устаревшее, но не мешает)
# SECURE_CONTENT_TYPE_NOSNIFF = not DEBUG  # Защита от MIME-type атак


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users.apps.UsersConfig",
    "dogs.apps.DogsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kennel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kennel.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_DATABASE"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR.parent, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.User"
LOGIN_REDIRECT_URL = "users:profile"
LOGOUT_REDIRECT_URL = "dogs:index"
LOGIN_URL = "/users/"

# Email newsletter
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.yandex.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = os.getenv("YANDEX_USER")
EMAIL_HOST_PASSWORD = os.getenv("YANDEX_PASSWORD_APP")
EMAIL_USE_TLS = False  # порт 587
EMAIL_USE_SSL = True  # порт 465

EMAIL_SERVER = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "{asctime} - {levelname} - {name} - {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname} - {name} - {message}",
#             "style": "{",
#         },
#         "error": {
#             "format": "{asctime} - {levelname} - {module} - {name} - {lineno:d} - {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         # Обработчик для записи логов в файл
#         "file": {
#             "level": "INFO",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs/info-file.log",
#             "formatter": "verbose",
#             "encoding": "utf-8",
#         },
#         # Обработчик для вывода логов в консоль
#         "console": {
#             "level": "INFO",
#             "class": "logging.StreamHandler",
#             "formatter": "simple",
#         },
#         # Отдельный обработчик ERROR для записи подробных логов в файл
#         "error_file": {
#             "level": "ERROR",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs/error-file.log",
#             "formatter": "error",
#             "encoding": "utf-8",
#         },
#     },
#     "loggers": {
#         # logger для django
#         "django": {
#             "handlers": ["file", "console"],
#             "level": "INFO",
#             "propagate": False,
#         },
#         # logger для ошибок в django
#         "django.request": {
#             "handlers": ["error_file"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#     },
# }

# apps = ["users", "dogs"]
# for app in apps:
#     LOGGING["loggers"][app] = {
#         "handlers": ["file", "console"],
#         "level": "INFO",
#         "propagate": False,
#     }
#     LOGGING["loggers"][f"{app}.errors"] = {
#         "handlers": ["error_file"],
#         "level": "ERROR",
#         "propagate": False,
#     }
